# Generated by Django 2.1.2 on 2018-11-02 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='list',
            name='url_key',
        ),
        migrations.AddField(
            model_name='list',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='task',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
