# Generated by Django 2.1.2 on 2018-12-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181125_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='creator',
        ),
    ]
