# Generated by Django 2.1.2 on 2019-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_list_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='sort',
            field=models.CharField(default='created_at', max_length=10),
        ),
    ]
