# Generated by Django 2.1.2 on 2019-03-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0010_adding_events_and_notified_list")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Profile",
            ),
        )
    ]
